name: 'Proyecto_League'
version: '1.0.0'
config-version: 2

profile: 'default'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"


models:
  Proyecto_League:
    league:
      1_staging:
        +database: SILVER_DEV
        +schema: staging
        +materialized: view
      2_marts:
        +database: GOLD_DEV
        +schema: marts
        +materialized: table