name: 'Proyecto_League'
version: '1.0.0'
config-version: 2

profile: 'default'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"


models:
  Proyecto_League:
    league:
      base:
        +materialized: view
        +database: "{{ 'SILVER_' ~ env_var('DBT_ENVIRONMENTS') }}"
        +schema: base
      1_staging:
        +materialized: view
        +database: "{{ 'SILVER_' ~ env_var('DBT_ENVIRONMENTS') }}"
        +schema: staging
      2_marts:
        +materialized: table
        +database: "{{ 'GOLD_' ~ env_var('DBT_ENVIRONMENTS') }}"
        +schema: marts